/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ArrayList;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Davi
 */
public class TelaArrayList extends javax.swing.JInternalFrame {

    List<String> list = new ArrayList<>();

    /**
     * Creates new form TelaArrayList
     */
    public TelaArrayList() {
        initComponents();
        
        list.add("Davi");
        list.add("Ricardo");
        list.add("Rafael");
        
        imprimirLista();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCampo = new java.awt.TextField();
        btCadastrar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btInserirPosicao = new javax.swing.JButton();
        btTamanho = new javax.swing.JButton();
        btRemoverNome = new javax.swing.JButton();
        btRemoverPosicao = new javax.swing.JButton();
        btPosicaoElemento = new javax.swing.JButton();
        btAlterarElemento = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btElementoLista = new javax.swing.JButton();
        btOrdenar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setMinimumSize(new java.awt.Dimension(813, 513));
        setPreferredSize(new java.awt.Dimension(500, 400));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Entrada de dados"));

        jLabel1.setText("Valor");

        btCadastrar.setText("Cadastrar");
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCampo, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(197, 197, 197)
                .addComponent(btCadastrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel1)
                    .addComponent(txtCampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btCadastrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Botões"));
        jPanel2.setLayout(new java.awt.GridLayout(4, 2));

        btInserirPosicao.setText("Inserir em uma posição");
        btInserirPosicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInserirPosicaoActionPerformed(evt);
            }
        });
        jPanel2.add(btInserirPosicao);

        btTamanho.setText("Tamanho da lista");
        btTamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTamanhoActionPerformed(evt);
            }
        });
        jPanel2.add(btTamanho);

        btRemoverNome.setText("Remover por nome");
        btRemoverNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverNomeActionPerformed(evt);
            }
        });
        jPanel2.add(btRemoverNome);

        btRemoverPosicao.setText("Remover por posição");
        btRemoverPosicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoverPosicaoActionPerformed(evt);
            }
        });
        jPanel2.add(btRemoverPosicao);

        btPosicaoElemento.setText("Posição do elemento");
        btPosicaoElemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPosicaoElementoActionPerformed(evt);
            }
        });
        jPanel2.add(btPosicaoElemento);

        btAlterarElemento.setText("Alterar elemento");
        btAlterarElemento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlterarElementoActionPerformed(evt);
            }
        });
        jPanel2.add(btAlterarElemento);

        btLimpar.setText("Limpar lista");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        jPanel2.add(btLimpar);

        btElementoLista.setText("Elemento da lista");
        btElementoLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btElementoListaActionPerformed(evt);
            }
        });
        jPanel2.add(btElementoLista);

        btOrdenar.setText("Ordenação");
        btOrdenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOrdenarActionPerformed(evt);
            }
        });
        jPanel2.add(btOrdenar);

        jButton1.setText("Imprimir lista");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(167, Short.MAX_VALUE))
        );

        setBounds(0, 0, 813, 513);
    }// </editor-fold>//GEN-END:initComponents

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        // TODO add your handling code here:

        list.add(txtCampo.getText());
        txtCampo.setText("");
        txtCampo.requestFocus();
        imprimirLista();


    }//GEN-LAST:event_btCadastrarActionPerformed

    private void btInserirPosicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInserirPosicaoActionPerformed
        // TODO add your handling code here:
        
        String nome = JOptionPane.showInputDialog("Informe o nome que deseja inserir: ");
        int posicao = Integer.parseInt(JOptionPane.showInputDialog("Informe a posição: "));
        
        list.add(posicao,nome);
        imprimirLista();
    }//GEN-LAST:event_btInserirPosicaoActionPerformed

    private void btTamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTamanhoActionPerformed
        // TODO add your handling code here:
        
        System.out.println("Tamanho da lista: "+list.size());
        System.out.println("===========================");
        
    }//GEN-LAST:event_btTamanhoActionPerformed

    private void btRemoverNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverNomeActionPerformed
        // TODO add your handling code here:
        
        String nome = JOptionPane.showInputDialog("Informe o nome que deseja remover: ");
        
        int confirma = JOptionPane.showConfirmDialog(null,"Tem certeza que deseja excluir o professor "+nome+" ?", "Atenção!!", JOptionPane.YES_NO_OPTION);
        if(confirma == JOptionPane.YES_OPTION){
            list.remove(nome);
            imprimirLista();
        }else{
            JOptionPane.showMessageDialog(null,"Professor não foi removido da lista!");
            imprimirLista();
        }
        
    }//GEN-LAST:event_btRemoverNomeActionPerformed

    private void btRemoverPosicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoverPosicaoActionPerformed
        // TODO add your handling code here:
        int posicao = Integer.parseInt(JOptionPane.showInputDialog("Informe a posição: "));
        
        list.remove(posicao);
        imprimirLista();
        
    }//GEN-LAST:event_btRemoverPosicaoActionPerformed

    private void btPosicaoElementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPosicaoElementoActionPerformed
        // TODO add your handling code here:
        String nome = JOptionPane.showInputDialog("Informe o nome que deseja descobrir a posição: ");
        
        System.out.println("Posição do elemento: "+list.indexOf(nome));
        System.out.println("===========================");        
        
        
    }//GEN-LAST:event_btPosicaoElementoActionPerformed

    private void btAlterarElementoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarElementoActionPerformed
        // TODO add your handling code here:
        
        String nome = JOptionPane.showInputDialog("Informe o nome que deseja alterar: ");
        
        String nomeNovo = JOptionPane.showInputDialog("Informe o novo nome do professor: ");
        
        list.set(list.indexOf(nome),nomeNovo);
        imprimirLista();
        
        
    }//GEN-LAST:event_btAlterarElementoActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        // TODO add your handling code here:
        list.clear();
        System.out.println("Lista vazia");
        imprimirLista();
        
    }//GEN-LAST:event_btLimparActionPerformed

    private void btElementoListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btElementoListaActionPerformed
        // TODO add your handling code here:
        int posicao = Integer.parseInt(JOptionPane.showInputDialog("Informe a posição: "));
        
        System.out.println("Elemento da posição "+posicao+": "+list.get(posicao));
        System.out.println("===========================");
    }//GEN-LAST:event_btElementoListaActionPerformed

    private void btOrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOrdenarActionPerformed
        // TODO add your handling code here:
        Collections.sort(list);
        imprimirLista();
        
    }//GEN-LAST:event_btOrdenarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        imprimirLista();
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlterarElemento;
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton btElementoLista;
    private javax.swing.JButton btInserirPosicao;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btOrdenar;
    private javax.swing.JButton btPosicaoElemento;
    private javax.swing.JButton btRemoverNome;
    private javax.swing.JButton btRemoverPosicao;
    private javax.swing.JButton btTamanho;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private java.awt.TextField txtCampo;
    // End of variables declaration//GEN-END:variables

    public void imprimirLista(){
        
        int cont = 0;
        for (String x : list){
            System.out.println(cont + " | "+ x);
            cont++;
        }
        System.out.println("===========================");
        
    }
    
}
